# Generated by Django 5.1.3 on 2024-11-26 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_number", models.CharField(max_length=300)),
                ("name", models.CharField(max_length=100)),
                ("Team", models.CharField(max_length=100)),
                ("designation", models.CharField(default="Technician", max_length=100)),
                ("Facility", models.CharField(max_length=100)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="Training/profile_pics"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "category",
                    models.CharField(default="EQUIPMENT MANUAL", max_length=20),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="Training/uploads/"
                    ),
                ),
                ("facility", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_pages", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Trainingsrequired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility", models.CharField(max_length=20)),
                ("Required_Module_trainings", models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name="CompletedTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_trainings",
                        to="Training.employeeprofile",
                    ),
                ),
                (
                    "training_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_by_profiles",
                        to="Training.trainingmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_completed"],
                "unique_together": {("employee", "training_module")},
            },
        ),
    ]
