# Generated by Django 5.1.3 on 2024-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0008_alter_trainingsrequired_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsrequired",
            name="Category",
            field=models.CharField(max_length=50),
        ),
    ]
