# Generated by Django 5.1.3 on 2024-12-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0010_alter_employeeprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedtraining",
            name="read_status",
            field=models.BooleanField(default=False),
        ),
    ]
