# Generated by Django 5.1.3 on 2024-12-01 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0011_completedtraining_read_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completedtraining",
            name="read_status",
        ),
        migrations.CreateModel(
            name="Readdocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_completed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("read_status", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_trainings_readdocuments",
                        to="Training.employeeprofile",
                    ),
                ),
                (
                    "training_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_by_profiles_readdocuments",
                        to="Training.trainingmodule",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "training_module")},
            },
        ),
    ]
